<a href="https://colab.research.google.com/github/lovelessbhartal12/ANN-codeplaces/blob/main/Word2vec_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import pandas as pd
import numpy as np

In [108]:
temp_df = pd.read_csv('/content/IMDB Dataset.csv', engine='python', on_bad_lines='skip')

In [109]:
temp_df.shape

(50000, 2)

In [110]:
df=temp_df.iloc[:20000]

In [111]:
df.shape

(20000, 2)

In [112]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [113]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [114]:
df['sentiment'].value_counts()

sentiment
negative    10097
positive     9903
Name: count, dtype: int64

In [115]:
df['review'].isnull().sum()

np.int64(0)

In [116]:
df.duplicated().sum()

np.int64(74)

In [117]:
df.drop_duplicates(inplace=True)

/tmp/ipython-input-3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [118]:
df.duplicated().sum()

np.int64(0)

In [119]:
import re

In [120]:
def remove_tag(remove_tag):
  remove_tag=re.compile(r'<.*?>').sub(r'',remove_tag)
  return remove_tag

In [121]:
df['review']=df['review'].apply(remove_tag)

/tmp/ipython-input-3179549256.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_tag)

In [122]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [123]:
df['review']=df['review'].apply(lambda x:x.lower())

/tmp/ipython-input-2697927567.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:x.lower())

In [124]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [125]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [126]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')

In [32]:
sw_list

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [127]:
df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x: " ".join(x))

/tmp/ipython-input-96325403.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x: " ".join(x))

In [128]:
df

                                                  review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production. filming technique...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically there's family little boy (jake) thi...  negative
4      petter mattei's "love time money" visually stu...  positive
...                                                  ...       ...
19995  ok. starters, taxi driver amazing. this, taxi ...  negative
19996  sort hard say it, greatly enjoyed "targets" "p...  negative
19997  still liked though. warren beatty fair comic b...  positive
19998  could still use black adder even today. imagin...  positive
19999  so-called "documentary" tries tell usa faked m...  negative

[19926 rows x 2 columns]

In [141]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.0.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 42.8 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [142]:
import gensim

In [148]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [149]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [152]:
story=[]
for doc in df['review']:
  raw_sent=sent_tokenize(doc)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [155]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [157]:
model.build_vocab(story)

In [158]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(11757392, 12360490)

In [161]:
def document_vec(doc):
  doc=[word for word in doc.split() if word in model.wv.index_to_key]
  return np.mean(model.wv[doc], axis=0)

In [162]:
document_vec(df['review'].values[0])

array([-0.00266602,  0.15418528, -0.0018295 ,  0.01837739,  0.3376583 ,
       -0.57178926,  0.18789321,  0.67982244, -0.03489799, -0.27169433,
        0.0890507 , -0.2681787 , -0.03975905,  0.00496472,  0.04491602,
       -0.14759779, -0.16698454, -0.30835274, -0.01406361, -0.1526931 ,
        0.2627398 ,  0.05237401,  0.18894881, -0.16996883, -0.05309892,
       -0.2191299 , -0.11589794, -0.19336365, -0.10832843,  0.03639678,
        0.6277814 ,  0.04792858, -0.14260465, -0.34695137,  0.0328489 ,
        0.4330261 , -0.08919352, -0.30217478, -0.2198208 , -0.6128714 ,
        0.09051024,  0.06875435, -0.04137226, -0.16562314,  0.2815174 ,
       -0.05318001, -0.29359716, -0.04491002,  0.19268693,  0.24259986,
        0.46403787, -0.4820932 ,  0.01492314, -0.45341042, -0.19853911,
        0.33541954,  0.37539598,  0.20101696, -0.3002957 ,  0.06279101,
        0.01078921,  0.32899028,  0.13977492,  0.12165201, -0.30351287,
        0.25781447, -0.07142255,  0.3325385 , -0.5545193 ,  0.3400143 ,
       -0.3075295 ,  0.38088924,  0.12906781,  0.02943485,  0.32888296,
       -0.10400962,  0.08372612, -0.13081989, -0.48796788,  0.251998  ,
        0.2861572 ,  0.07539516, -0.31466097,  0.32858488, -0.2793976 ,
       -0.12398737,  0.12938328,  0.14801145,  0.30379108,  0.18476726,
        0.46727595,  0.43253472,  0.15411116,  0.14864843,  0.50166935,
        0.47321153, -0.3552778 , -0.2133893 , -0.13665363,  0.03261753],
      dtype=float32)

In [163]:
from tqdm import tqdm

In [165]:
x=[]
for doc in tqdm(df['review'].values):
  x.append(document_vec(doc))

100%|██████████| 19926/19926 [19:37<00:00, 16.92it/s]

In [166]:
x=np.array(x)

In [167]:
x.shape

(19926, 100)

In [168]:
y=df['sentiment']

In [169]:
y.head()

0    positive
1    positive
2    positive
3    negative
4    positive
Name: sentiment, dtype: object

In [170]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [171]:
y=label.fit_transform(y)

In [172]:
y

array([1, 1, 1, ..., 1, 1, 0])

In [173]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.20, random_state=1)

In [174]:
x_train.shape

(15940, 100)

In [175]:
x_test.shape

(3986, 100)

In [138]:
x_train = x_train.astype(str)
x_test = x_test.astype(str)

In [176]:
 from sklearn.ensemble import RandomForestClassifier
 from sklearn.metrics import accuracy_score

In [177]:
rf1=RandomForestClassifier()

In [178]:
rf1.fit(x_train,y_train)

RandomForestClassifier()

In [179]:
y_pred=rf1.predict(x_test)

In [180]:
accuracy_score(y_test, y_pred)

0.8028098344204716